AllCops:
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
